export const REGISTER_INIT = "auth/REGISTER_INIT";
export const REGISTER_SUCCESS = "auth/REGISTER_SUCCESS";

export const LOAD_USER_INIT = "auth/LOAD_USER_INIT";
export const LOAD_USER_SUCCESS = "auth/LOAD_USER_SUCCESS";

export const LOGIN_INIT = "auth/LOGIN_INIT";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";

export const LOGIN_GOOGLE_INIT = "auth/LOGIN_GOOGLE_INIT";
export const LOGIN_GOOGLE_SUCCESS = "auth/LOGIN_GOOGLE_SUCCESS";

export const RECOVER_PASSWORD_INIT = "auth/RECOVER_PASSWORD_INIT";
export const RECOVER_PASSWORD_SUCCESS = "auth/RECOVER_PASSWORD_SUCCESS";

export const VALIDATE_EMAIL_INIT = "auth/VALIDATE_EMAIL_INIT";
export const VALIDATE_EMAIL_SUCCESS = "auth/VALIDATE_EMAIL_SUCCESS";

export const REFRESH_CODE_INIT = "auth/REFRESH_CODE_INIT";
export const REFRESH_CODE_SUCCESS = "auth/REFRESH_CODE_SUCCESS";

export const COMPLETE_PROFILE_INIT = "auth/COMPLETE_PROFILE_INIT";
export const COMPLETE_PROFILE_SUCCESS = "auth/COMPLETE_PROFILE_SUCCESS";

export const GET_AFFILIATES_INIT = "auth/GET_AFFILIATES_INIT";
export const GET_AFFILIATES_SUCCESS = "auth/GET_AFFILIATES_SUCCESS";

export const LOGOUT_INIT = "auth/LOGOUT_INIT";
export const LOGOUT_SUCCESS = "auth/LOGOUT_SUCCESS";

export const CLEAR_ERROR = "auth/CLEAR_ERROR";

export const API_ERROR = "auth/AUTH_ERROR";
