export const addAccountFormFields = {
  accType: '',
  account_number: '',
  alias: '',
  bankId: null,
  cci: '',
  currencyId: null,
  documentIdentity: '',
  documentNumberJoint: '',
  documentType: '',
  documentTypeJoint: '',
  email: '',
  firstName: '',
  firstNameJoint: '',
  isDirect: true,
  isThird: false,
  job: '',
  joint: false,
  lastName: '',
  lastNameJoint: '',
  razonSocial: '',
  thirdPartyAccType: 'natural',
  name: '',
}
